name: "Lint"

on:
  push:
    branches: [ "main", "feat/golangci_lint" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
